export const RECIPES = 'recipes'
export const INGREDIENTS = 'ingredients'
export const USERS = 'users'
export const LIST_TABLE = 'list_table'
export const LIST_CARD = 'list_card'
export const STARTERS = 'starters'
export const DISH = 'dish'
export const DESERTS = 'deserts'
