export const getHomeRoute = () => '/home'
export const getLoginRoute = () => '/login'
export const getLogoutRoute = () => '/logout'
export const getRecipesRoute = () => '/recipes'
export const getDesertsRoute = () => '/deserts'
export const getStartersRoute = () => '/starters'
export const getDishRoute = () => '/dish'
